name = "life-drive-test"
compatibility_date = "2026-09-12"
pages_build_output_dir = "public"
[[d1_databases]]
binding = "DB"
database_name = "life-drive-test"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"
preview_database_id = "DB"
