-- LEGACY / OPTIONAL. V5 no longer requires this migration for referrals.
-- visitor_id is stored inside events.payload so existing production D1 schemas work without ALTER TABLE.
-- Leave this file in the repository; do not apply it unless you explicitly want the extra visitor_id column.
